### ISSUE TITLE
Soilsens V5W - Text Sensor

### ISSUE THREAD

**Issue by DirkTas67** [PricelessToolkit/SOILSENS-V5W#9]
Hello,

I was wondering what the Text sensor is for the Soilsens v5w, I don't know if you shipped it this way to me but I had some problems installing the sensor, I eventualy had to 'reset' it with the 'plugin power/hold the calibration button' trick before it worked but that was after I re-installed the firmware, so now I have a text sensor that is changing rapidly and I wonder if this is good for the battery (still don't have a battery, it is powered directly from usb via pogo pins).

![Schermafdruk van 2024-12-15 10-30-40](https://github.com/user-attachments/assets/da95a913-e8fa-4ee2-9e6a-705a2c1a5702)

**Comment by DirkTas67** [comment]
![Schermafdruk van 2024-12-15 10-45-09](https://github.com/user-attachments/assets/9e5faf5b-6941-4367-9bf5-90c42591ca9c)

This is what the serial monitor tells us.

**Comment by PricelessToolkit** [comment]
Hi, Thank you for supporting my work! 
The "text" sensor is a raw ADC reading from the "moisture sensor." It can be handy for checking calibration. The serial output is normal but can appear to freak out because the sensor sends data too quickly, with no delay between readings. This happens because you powered it from the programming port, so the sensor can't "unplug itself" from power after sending data once. When you power it with a battery, it will work properly.
